functions = [
    "Voice Assistant",
    "Lighting",
    "Thermostat",
    "Plug",
    "Camera",
    "Lock",
    "Refrigerator",
    "Washing Machine",
    "Sensor",
    "Connected Vehicle",
    "Hub",
    "Smart TV",
    "Speaker",
    "Air Quality Monitor",
    "Smoke and CO Detector",
    "Health Device",
    "Robot Vacuum",
    "Fan",
    "Smartwatch",
    "Baby Monitor"
    ]