functions = [
    "Voice Assistant",
    "Smart Lighting",
    "Smart Thermostat",
    "Plug",
    "Security Camera",
    "Health Wearable",
    "Smart Lock",
    "Smart Appliance",
    "Smart Refrigerator",
    "Smart Washing Machine",
    "Smart Meter",
    "Smart Sensor",
    "Connected Vehicle",
    "Smart Home Hub",
    "Smart TV",
    "Smart Speaker",
    "Air Quality Monitor",
    "Smart Blinds",
    "Smart Faucet",
    "Smart Irrigation",
    "Smoke and CO Detector",
    "Smart Health Device",
    "Smart Mirror",
    "Robot Vacuum",
    "Smart Garage Door Opener",
    "Smart Outlet",
    "Smart Kitchen Device",
    "Smart Fan",
    "Smart Pet Device",
    "Smartwatch",
    "Motion Sensor",
    "Baby Monitor",
    "Fitness Band",
    "Chiller Monitor"
]