functions = [
    "Voice Assistant",
    "Smart Lighting",
    "Smart Thermostat",
    "Plug",
    "Security Cameras",
    "Health Wearables",
    "Smart Lock",
    "Smart Appliance",
    "Smart Refrigerator",
    "Smart Washing Machine",
    "Smart Meters",
    "Smart Sensor",
    "Connected Vehicle",
    "Smart Home Hub",
    "Smart TV",
    "Smart Speakers",
    "Air Quality Monitoring",
    "Smart Blinds",
    "Smart Faucets",
    "Smart Irrigation",
    "Smoke and CO Detectors",
    "Smart Health Devices",
    "Smart Mirrors",
    "Robot Vacuums",
    "vacuum cleaner"
    "Smart Garage Door Openers",
    "Smart Outlets",
    "Smart Kitchen Devices",
    "Smart Fans",
    "Smart Pet Devices",
    "Amazon Echo",
    "Footbot air quality monitor",
    "Amazon Dash Button",
    "Google Home voice Controller",
    "Smartwatch",
    "smart watch",
    "Camera",
    "Nest",
    "NETGEAR",
    "Smart Appliances",
    "Thermostats",
    "motion sensor",
    "Bitdefender",
    "Connected Cars",
    "Home Security",
    "Smart Outlets",
    "Smart TV",
    "Chamberlain myQ",
    "Chillers Monitor",
    "Fitness Band",
    "Healthcare",
    "Philips Hue bulbs and lighting system",
    "Baby Monitors",
    "Canary"
]
