vendor_function_map = {
    "amazon": ["Smart Speakers", "Smart Outlets", "Smart Home Hub", "Voice Assistant", "Smart TV"],
    "google": ["Smart Speakers", "Voice Assistant", "Smart TV"],
    "samsung": ["Smart TV", "Smart Refrigerator", "Smart Washing Machine", "Smart Home Hub", "Smartwatch"],
    "apple": ["Smartwatch", "Health Wearables", "Smart Speakers"],
    "bosch": ["Smart Kitchen Appliances", "Smart Sensor", "Smart Thermostat"],
    "honeywell": ["Smart Thermostat", "Smoke and CO Detectors", "Air Quality Monitoring", "Smart Lock"],
    "philips": ["Smart Lighting"],
    "nest": ["Smart Thermostat", "Security Cameras", "Smart Smoke Detectors"],
    "netgear": ["Security Cameras", "Smart Router", "Smart Home Hub"],
    "dji enterprise": ["Drone"],
    "canary": ["Security Cameras"],
    "fitbit": ["Health Wearables", "Smartwatch"],
    "tesla": ["Smart Car"],
    "johnson controls": ["Smart Thermostat", "Smart Building Systems"],
    "cisco": ["Smart Router", "IoT Network Gateway"],
    "siemens": ["Industrial Sensor", "Smart Meters", "Automation Devices"],
    "schneider electric": ["Smart Meters", "Industrial Monitoring", "Smart Thermostat"],
    "abb": ["Industrial Automation", "Smart Meters"],
    "panasonic": ["Smart TV", "Smart Appliances", "Security Cameras"],
    "dell": ["Edge Devices", "IoT Gateways"],
    "intel": ["Edge Devices", "IoT Modules", "Smart Cameras"],
    "nvidia": ["Smart Camera", "Edge AI Module"],
    "ibm": ["Smart Hub", "Smart Monitoring", "IoT Analytics Platform"],
    "microsoft": ["IoT Gateway", "Smart Hub", "Voice Assistant (Cortana)"],
    "particle": ["IoT Module", "Smart Sensor"],
    "relayr": ["Industrial Sensors", "Smart Monitoring"],
    "hpe": ["IoT Edge Gateway", "Analytics Gateway"],
    "advantech": ["Industrial Sensors", "IoT Gateway"],
    "general electric": ["Smart Meters", "Industrial Equipment Monitoring"],
    "edimax": ["Plug", "Camera", "Motion Sensor", "Hub"],
    "piper": ["Security Camera", "Home Monitoring", "Motion Detection", "Environmental Sensor", "Smart Home Hub"],
    "insteon": ["Hub", "Plug", "Door Sensor", "Motion Sensor", "Light switch"],
    "xiaomi": ["Camera", "bulb", "plug", "thermostat", "vacuum cleaner", "smartwatch", "smart tv", "air purifier"],
    "roku": ["smart tv", "streaming device", "camera", "plug", "lights", "video doorbell", "home monitoring"],
}
