vendor_function_map = {
    "amazon": ['Smart Speakers', 'Smart Outlets', 'Smart Home Hub', 'Voice Assistant', 'Smart TV', 'media streamer'],
    "apple": ['Smartwatch', 'Smart Speakers', 'smartphone', 'smart speaker'],
    "belkin": ['plug', 'smart switch', 'bulb', 'motion sensor', 'camera', 'hub'],
    "blink": ['video doorbell', 'camera'],
    "bosch": ['Smart Kitchen Appliances', 'Smart Sensor', 'Smart Thermostat'],
    "canary": ['Security Cameras'],
    "caseta": ['plug', 'switch', 'motion sensor', 'smart remote', 'hub'],
    "cisco": ['Smart Router', 'IoT Network Gateway', "smart city infrastucture"],
    "d-link": ['router', 'switch', 'camera', 'plug', 'wi-fi extender'],
    "digi": ["gateways", "industrial router", "mesh networking", "embedded system"],
    "dji enterprise": ['Drone'],
    "eaton": ["gateway"],
    "edimax": ['Plug', 'Camera', 'Motion Sensor', 'Hub'],
    "eseye": ["router"],
    "fitbit": ['Smartwatch'],
    "google": ['Smart Speakers', 'Voice Assistant', 'Smart TV', 'Smart Thermostat', 'Smart Security Camera', 'Smart Doorbell', 'Smart Smoke Detector'],
    "hitachi": [],
    "honeywell": ['Smart Thermostat', 'Smoke and CO Detectors', 'Air Quality Monitoring', 'Smart Lock'],
    "hp": ['printer', 'hub'],
    "hpe": ['IoT Edge Gateway', 'Analytics Gateway'],
    "huawei": [],
    "ibm": ['Smart Hub', 'Smart Monitoring', 'IoT Analytics Platform'],
    "impinj": [],
    "inductive automation": [],
    "infineon": ["smart home", "wearables", "smart sensors"],
    "infor": [],
    "ingenu": [],
    "insteon": ['Hub', 'Plug', 'Door Sensor', 'Motion Sensor', 'Light switch'],
    "intel": ['Edge Devices', 'IoT Modules', 'Smart Cameras'],
    "irobot": ['robot vacuum'],
    "john deere": [],
    "johnson controls": ['Smart Thermostat', 'Smart Building Systems'],
    "juniper networks": [],
    "lantronix": [],
    "microchip technology": [],
    "micron technology": [],
    "microsemi corporation": [],
    "microsoft": ['IoT Gateway', 'Smart Hub', 'Voice Assistant'],
    "mitsubishi": [],
    "moxa": [],
    "nec": [],
    "netatmo": ['video doorbell', 'air monitor', 'door sensor'],
    "netgear": ['Security Cameras', 'Smart Router', 'Smart Home Hub'],
    "ni": [],
    "nokia": [],
    "nvidia": ['Smart Camera', 'Edge AI Module'],
    "nxp semiconductors": [],
    "omron industrial automation": [],
    "on semiconductor": [],
    "osisoft": [],
    "panasonic": ['Smart TV', 'Smart Appliances', 'Security Cameras'],
    "particle": ['IoT Module', 'Smart Sensor'],
    "philips": ['Smart Lighting'],
    "phoenix contact": [],
    "piper": ['Security Camera', 'Home Monitoring', 'Motion Detection', 'Environmental Sensor', 'Smart Home Hub'],
    "proglove": [],
    "ptc": [],
    "pulse electronics": [],
    "qualcomm": [],
    "raytheon technologies": [],
    "relayr": ['Industrial Sensors', 'Smart Monitoring'],
    "rockwell automation": [],
    "roku": ['smart tv', 'streaming device', 'camera', 'plug', 'lights', 'video doorbell', 'home monitoring'],
    "samsara": [],
    "samsung": ['Smart TV', 'Smart Refrigerator', 'Smart Washing Machine', 'Smart Home Hub', 'Smartwatch'],
    "sap": [],
    "schneider electric": ['Smart Meters', 'Industrial Monitoring', 'Smart Thermostat'],
    "siemens": ['Industrial Sensor', 'Smart Meters', 'Automation Devices'],
    "sierra wireless": [],
    "sigfox": [],
    "silicon labs": [],
    "silver spring networks": [],
    "smartthings": [],
    "sonos": ['smart speaker', 'multi room audio', 'home theater system', 'voice assistant'],
    "sparkcognition": [],
    "stmicroelectronics": [],
    "te connectivity": [],
    "telefonica": [],
    "telit": [],
    "telstra": [],
    "tesla": ['Smart Car'],
    "texas instruments": [],
    "toshiba": [],
    "trumpf": [],
    "tyco electronics": [],
    "vantiq": [],
    "vodafone": [],
    "wansview": ['camera', 'automatic pet feeder', 'bulb'],
    "wibu-systems": [],
    "worldsensing": [],
    "wyze": ['camera', 'video doorbell', 'smart lock', 'smart lighting'],
    "xiaomi": ['Camera', 'bulb', 'plug', 'thermostat', 'vacuum cleaner', 'smartwatch', 'smart tv', 'air purifier'],
    "zebra technologies": [],
    "zscaler": [],
}
