vendor_function_map = {
    "amazon": ['Smart Speaker', 'Smart Outlets', 'Smart Home Hub', 'Voice Assistant', 'Smart TV', 'Media Streamer'],
    "apple": ['Smartwatch', 'Smart Speaker', 'Smartphone', 'iPad', 'Laptop'],
    "belkin": ['Smart Plug', 'Smart Switch', 'Smart Bulb', 'Smart Sensor', 'Smart Camera', 'Smart Home Hub'],
    "blink": ['Video Doorbell', 'Smart Camera'],
    "bosch": ['Smart Kitchen Appliances', 'Smart Sensor', 'Smart Thermostat'],
    "canary": ['Smart Camera'],
    "caseta": ['Smart Plug', 'Smart Switch', 'Smart Sensor', 'Smart Remote', 'Smart Home Hub'],
    "cisco": ['Smart Router', 'IoT Network Gateway', "Smart City infrastucture"],
    "d-link": ['Router', 'Smart Switch', 'Smart Camera', 'Smart Plug', 'wi-fi extender'],
    "digi": ["gateways", "industrial router", "mesh networking", "embedded system"],
    "dji enterprise": ['Drone'],
    "eaton": ["gateway"],
    "edimax": ['Plug', 'Camera', 'Sensor', 'Hub'],
    "eseye": ["Router"],
    "fitbit": ['Smartwatch'],
    "google": ['Smart Speaker', 'Voice Assistant', 'Smart TV', 'Smart Thermostat', 'Smart Camera', 'Smart Doorbell', 'Smart Smoke Detector'],
    "honeywell": ['Smart Thermostat', 'Air Quality Sensor', 'Smart Lock', 'Smart Camera', 'Security System', 'Smart Doorbell'],
    "hp": ['Smart Printer', 'Smart Home Hub'],
    "huawei": ["Smartphone", "Smart TV", "Smart Speaker", "Router", "Smart Camera", "Smart Home Hub", "Smartwatch", "Smart Plug", "Smart Bulb"],
    "impinj": ["RFID Reader", "RFID Gateway"],
    "xiaoyi": ["Smart Camera"],
    "infineon": ["smart home", "wearables", "Smart Sensor"],
    "insteon": ['Hub', 'Plug', 'Door Sensor', 'Motion Sensor', 'Light switch'],
    "irobot": ['Robot Vacuum'],
    "johnson controls": ['Smart Thermostat', 'Smart HVAC Unit', 'Environmental Sensor', 'Security Camera', 'Smart Lock'],
    "moxa": ['IIoT Gateways', 'Remote I/O Modules', 'Serial Device Servers', 'Industrial Routers', 'Smart Camera'],
    "netatmo": ['video doorbell', 'air monitor', 'Door Sensor'],
    "netgear": ["WiFi Router", "Smart Home Hub", "Smart Switch"],
    "nokia": ["media streamer", "laptop"],
    "nvidia": ['streaming media device'],
    "omron industrial automation": ['robot', 'Sensor', 'industiral switch'],
    "panasonic": ['Smart TV', 'Smart Camera', 'Baby Monitor', 'Massage Chair'],
    "philips": ['Smart Lighting', 'Smart TV', 'Smart ear Thermometer'],
    "piper": ['Camera', 'Smart Switch'],
    "proglove": ["Smart Wearable Scanner"],
    "qualcomm": ['Smartphone', 'Smart Speaker'],
    "relayr": ['Industrial Sensors', 'IoT Gateway'],
    "rockwell automation": ['Sensor', 'Industrial Gateway', 'Switch'],
    "roku": ['Smart tv', 'streaming device', 'Smart Camera', 'plug', 'lights', 'video doorbell', 'home monitoring'],
    "samsara": ['Vehicle Gateway', 'Smart Camera', 'Industrial Controller'],
    "samsung": ['Smart TV', 'Refrigerator', 'Washing Machine', 'Smartwatch', 'Speaker', 'Smart Camera', 'Smartphone'],
    "smartthings": ['Hub', 'Plug', 'Bulb', 'Lock', 'Sensor', 'Thermostat'],
    "sierra wireless": ['IoT gateway', 'Cellular routers', 'Tracking devices'],
    "sonos": ['smart speaker', 'multi room audio', 'home theater system', 'Voice Assistant'],
    "telit": ["IoT Gateway", "Router"],
    "telstra": ["IoT Gateway", "Router"],
    "tesla": ['Smart Car', "Smart EV Charger", "Home Battery System", "Solar Inverter"],
    "toshiba": ['Smart TV', 'Router'],
    "wansview": ['Smart Camera', 'automatic pet feeder', 'bulb'],
    "worldsensing": [  "Wireless Data Logger", "Vibration Meter", "Piconode Data Logger"],
    "wyze": ['Smart Camera', 'video doorbell', 'smart lock', 'smart lighting'],
    "xiaomi": ['Camera', 'bulb', 'plug', 'thermostat', 'vacuum cleaner', 'smartwatch', 'Smart TV', 'air purifier', 'smartphone'],
    "zebra technologies": ['Barcode Scanner', 'Radio Frequency Identification Reader', 'Tablet', 'Inventory Management System', 'Location Tracking Device', 'Printer', 'Mobile Computer'],
    "lg": ['Smart TV', 'Smart Monitor', 'smart refrigerator', 'Smart Microwave', 'Smart Gas', 'Smart Oven', 'Laptop', 'Smart Air Conditioner'],
    "tp-link": ['Wi-Fi Router', 'Smart Plug', 'Smart Bulb', 'Smart Camera', 'Smart Switch', 'Hub', 'Robot Vacuum', 'Sensor'],
    "lifx": ['Smart Switch', 'Smart Bulb'],
    "august home": ['Smart Lock', 'Smart Door Bundle'],
    "vizio": ['Smart TV', 'Smart Soundbar'],
    "ecovacs": ['Robot Vacuum'],
    "withings": ['Smartwatch', 'Smart Scale'],
    "logitech": ['Camera'],
    "neato": ['Robot Vacuum']
}
